# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mv_normal <- function(mu, sigma) {
    .Call(`_geblm_mv_normal`, mu, sigma)
}

uv_gamma <- function(shape, rate) {
    .Call(`_geblm_uv_gamma`, shape, rate)
}

lm_proper_cpp <- function(X, y, beta_prior_mean, beta_prior_cov, tau_prior_shape, tau_prior_rate, iterations, burnin, thin, start_beta) {
    .Call(`_geblm_lm_proper_cpp`, X, y, beta_prior_mean, beta_prior_cov, tau_prior_shape, tau_prior_rate, iterations, burnin, thin, start_beta)
}

