# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

conv_check_lmm_improper <- function(x, y, z, a, b) {
    .Call(`_geblm_conv_check_lmm_improper`, x, y, z, a, b)
}

mv_normal <- function(mu, sigma) {
    .Call(`_geblm_mv_normal`, mu, sigma)
}

uv_gamma <- function(shape, rate) {
    .Call(`_geblm_uv_gamma`, shape, rate)
}

lm_proper_cpp <- function(X, y, beta_prior_mean, beta_prior_cov, tau_prior_shape, tau_prior_rate, iterations, burnin, thin, start_beta) {
    .Call(`_geblm_lm_proper_cpp`, X, y, beta_prior_mean, beta_prior_cov, tau_prior_shape, tau_prior_rate, iterations, burnin, thin, start_beta)
}

lmm_improper_cpp <- function(X, Z, y, lambda_prior_shape, lambda_prior_rate, iterations, burnin, thin, start_theta) {
    .Call(`_geblm_lmm_improper_cpp`, X, Z, y, lambda_prior_shape, lambda_prior_rate, iterations, burnin, thin, start_theta)
}

lmm_proper_cpp <- function(x, z, y, beta_prior_mean, beta_prior_cov, lambda_prior_shape, lambda_prior_rate, iterations, burnin, thin, start_theta) {
    .Call(`_geblm_lmm_proper_cpp`, x, z, y, beta_prior_mean, beta_prior_cov, lambda_prior_shape, lambda_prior_rate, iterations, burnin, thin, start_theta)
}

